//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.4
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _PARAMETERTASK_HH
#define _PARAMETERTASK_HH

#include "gen/ParameterTaskCore.hh"
#include <CommManipulationPlannerObjects/commManipulationPlannerParameter.hh>

class ParameterTask: public ParameterTaskCore
{

public:
	ParameterTask();
	int svc();

	void pushParam(const CommManipulationPlannerObjects::CommManipulationPlannerParameter& param);
	void waitQueueEmpty();

private:
	std::queue<CommManipulationPlannerObjects::CommManipulationPlannerParameter> paramQueue;
	CHS::SmartSemaphore paramQueueSemaphore;
	CHS::SmartMutex m;
	CHS::SmartConditionMutex cond;
};

#endif
