// --------------------------------------------------------------------------
//
//  Copyright (C) 2008 Christian Schlegel, Andreas Steck
//
//        schlegel@hs-ulm.de
//        steck@hs-ulm.de 
//
//        ZAFH Servicerobotik Ulm
//        University of Applied Sciences
//        Prittwitzstr. 10
//        D-89075 Ulm
//        Germany
//
//  This file is part of the "SmartSoft Communication Classes".
//  It provides basic standardized data types for communication between
//  different components in the mobile robotics context. These classes
//  are designed to be used in conjunction with the SmartSoft Communication
//  Library.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --------------------------------------------------------------------------

#ifndef _SMART_IDL_GRIDMAP
#define _SMART_IDL_GRIDMAP

#include "smartTimeStamp.idl"

module SmartIDL 
{

  struct GridMap
  {
    // identifies global frame of reference
    unsigned long id;

    //
    boolean is_valid;

    // the timestamp of the scan
    TimeStamp time;

    // offset of the map in mm relative to world coordinate system
    long xOffsetMM;
    long yOffsetMM;

    // offset of the map in cells relative to the world coordinate system
    long xOffsetCells;
    long yOffsetCells;

    // size of one cell in mm
    unsigned long cellSizeMM;

    // size of the map in mm
    unsigned long xSizeMM;
    unsigned long ySizeMM;

    // size of gridmap in number of cells in direction of x and y
    unsigned long xSizeCells;
    unsigned long ySizeCells;

    // total size of gridmap in number of cells
    unsigned long size;

    //  
    sequence<octet> cell;

  };
};

#endif

