//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _EVENTTESTHANDLER_HH
#define _EVENTTESTHANDLER_HH

#include "smartSoft.hh"

// include communication objects
#include <CommSpeechObjects/commSpeechInputEventParameter.hh>
#include <CommSpeechObjects/commSpeechInputEventResult.hh>
#include <CommSpeechObjects/commSpeechInputParameter.hh>
#include <CommSpeechObjects/speechInputEventState.hh>

#include "gen/EventTestHandlerCore.hh"

class EventTestHandler: public EventTestHandlerCore
{
	bool testEvent(CommSpeechObjects::CommSpeechInputEventParameter &p,
			CommSpeechObjects::CommSpeechInputEventResult &r,
			const CommSpeechObjects::SpeechInputEventState &s) throw();
};

#endif
