//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _PARAMHANDLER_HH
#define _PARAMHANDLER_HH

#include "smartSoft.hh"

#include "gen/ParamHandlerCore.hh"

class ParamHandler: public ParamHandlerCore
{
	void
			handleSend(const CommSpeechObjects::CommSpeechInputParameter &r) throw();
};

#endif
