//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.8.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CompHandler.hh"
#include "gen/SampleEventClient.hh"

#include <iostream>

// include communication objects
#include <CommSampleObjects/commSampleEvent1Parameter.hh>

#include <CommSampleObjects/commSampleEvent1Result.hh>

void CompHandler::onStartup()
{
	std::cout
			<< "startup - put your startupCode in CompHandler::onStartup()!!!\n";

	CHS::StatusCode status;

	// connect to all services
	std::cout << "connecting to: " << COMP->ini.eventClient1.serverName << "; "
			<< COMP->ini.eventClient1.serviceName << std::endl;
	status = COMP->eventClient1->connect(COMP->ini.eventClient1.serverName,
			COMP->ini.eventClient1.serviceName);
	while (status != CHS::SMART_OK)
	{
		usleep(500000);
		status = COMP->eventClient1->connect(COMP->ini.eventClient1.serverName,
				COMP->ini.eventClient1.serviceName);
	}
	std::cout << "connected.\n";

	std::cout << "connecting to: " << COMP->ini.eventClient2.serverName << "; "
			<< COMP->ini.eventClient2.serviceName << std::endl;
	status = COMP->eventClient2->connect(COMP->ini.eventClient2.serverName,
			COMP->ini.eventClient2.serviceName);
	while (status != CHS::SMART_OK)
	{
		usleep(500000);
		status = COMP->eventClient2->connect(COMP->ini.eventClient2.serverName,
				COMP->ini.eventClient2.serviceName);
	}
	std::cout << "connected.\n";

	// run all tasks
	COMP->myEventTask.open();

	// activate event
	CommSampleObjects::CommSampleEvent1Parameter parameter;
	CHS::EventId               id;

	parameter.set(5);
	status = COMP->eventClient2->activate(CHS::single, parameter, id);

}
