//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _SMARTUNICAPIMAGECLIENTCORE_HH
#define _SMARTUNICAPIMAGECLIENTCORE_HH

#include <iostream>
#include <cv.h>
#include <highgui.h>
#include <CommVisionObjects/commVideoImage.hh>
#include <smartSoft.hh>
#include "OpenCVHelpers.hh"

class SmartUnicapImageClientCore
{
private:

public:
	SmartUnicapImageClientCore();
	IplImage* convertDataArrayToIplImage(CommVisionObjects::CommVideoImage &query_image, CvSize size);

	IplImage* currentImage;
	CHS::SmartMutex CurrentImageMutex;
};

#endif
