//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

// --------------------------------------------------------------------------
//
//  Copyright (C) 2009 Andreas Steck, Matthias Lutz
//
//        schlegel@hs-ulm.de
//
//        Prof. Dr. Christian Schlegel
//        University of Applied Sciences
//        Prittwitzstr. 10
//        D-89075 Ulm
//        Germany
//
//  This file is part of the "SmartSoft Communication Library".
//  It provides standardized patterns for communication between
//  different components.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --------------------------------------------------------------------------

#include "commSpeechInputEventResult.hh"

using namespace CommSpeechObjects;

void CommSpeechInputEventResult::get(CORBA::Any &a) const
{
	a <<= idl_CommSpeechInputEventResult;
}

void CommSpeechInputEventResult::set(const CORBA::Any &a)
{
	CommSpeechObjectsIDL::CommSpeechInputEventResult *tmp_cmd;
	if (a >>= tmp_cmd)
	{
		idl_CommSpeechInputEventResult = *tmp_cmd;
	}
}

void CommSpeechInputEventResult::set_text(std::string text)
{
	idl_CommSpeechInputEventResult.text = text.c_str();
}

std::string CommSpeechInputEventResult::get_text() const
{
  return (const char*)idl_CommSpeechInputEventResult.text;
}

void CommSpeechInputEventResult::set_semantic(std::string semantic)
{
	idl_CommSpeechInputEventResult.semantic = semantic.c_str();
}

std::string CommSpeechInputEventResult::get_semantic() const
{
  return (const char*)idl_CommSpeechInputEventResult.semantic;
}

void CommSpeechInputEventResult::set_confidence(double confidence)
{
	idl_CommSpeechInputEventResult.confidence = confidence;
}

double CommSpeechInputEventResult::get_confidence() const
{
  return idl_CommSpeechInputEventResult.confidence;
}

