//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _SPEECHQUERYHANDLER_HH
#define _SPEECHQUERYHANDLER_HH

#include "smartSoft.hh"

// include communication objects
#include <CommBasicObjects/commPropertySet.hh>

#include <CommSpeechObjects/commSpeechOutputMessage.hh>

#include "gen/SpeechQueryHandlerCore.hh"

class SpeechQueryHandler: public SpeechQueryHandlerCore
{
	void handleQuery(CHS::QueryServer<
			CommSpeechObjects::CommSpeechOutputMessage,
			CommBasicObjects::CommPropertySet> & server, const CHS::QueryId id,
			const CommSpeechObjects::CommSpeechOutputMessage & request) throw();
};

#endif
