//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.4
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------
//------------------------------------------------------------------------
//
//  Copyright (C) 2011 Manuel Wopfner
//
//        wopfner@hs-ulm.de
//
//        Christian Schlegel (schlegel@hs-ulm.de)
//        University of Applied Sciences
//        Prittwitzstr. 10
//        89075 Ulm (Germany)
//
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//--------------------------------------------------------------------------

#ifndef _COMM_COMMPERSONDETECTIONOBJECTS_COMMPERSONID_HH
#define _COMM_COMMPERSONDETECTIONOBJECTS_COMMPERSONID_HH

#include <string>

// include files of classes

// include header-files of included communication objects

// include enums


// include client-side file generated by IDL compiler
#include "CommPersonDetectionObjects/gen/smartCommPersonIdC.hh"

namespace CommPersonDetectionObjects
{

class CommPersonId
{
protected:
	CommPersonDetectionObjectsIDL::CommPersonId idl_CommPersonId;

public:
	CommPersonId()
	{
	}

	CommPersonId(const CommPersonDetectionObjectsIDL::CommPersonId &obj) :
		idl_CommPersonId(obj)
	{
	}

	virtual ~CommPersonId()
	{
	}

	operator CommPersonDetectionObjectsIDL::CommPersonId() const
	{
		return idl_CommPersonId;
	}

	void get(CORBA::Any &a) const;
	void set(const CORBA::Any &a);

	static inline std::string identifier(void)
	{
		return "CommPersonDetectionObjects::CommPersonId";
	}

	//
	// user interfaces


	void set_person_id(uint32_t id)
	{
		idl_CommPersonId.id = id;
	}

	uint32_t get_person_id() const
	{
		return idl_CommPersonId.id;
	}
};

}
#endif
