//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _SMARTTTSLOQUENDOCORE_HH
#define _SMARTTTSLOQUENDOCORE_HH

#include "smartSoft.hh"
#include <iostream>
#include "CommBasicObjects/commPropertySet.hh"
#include "CommSpeechObjects/commSpeechOutputMessage.hh"

class SmartTTSLoquendoCore
{
private:




public:
	SmartTTSLoquendoCore();

	  struct QueueEntry
	  {
	    QueueEntry(const CommSpeechObjects::CommSpeechOutputMessage &m)
	    : msg(m), query_server(0) {}

	    QueueEntry(const CommSpeechObjects::CommSpeechOutputMessage &m, CHS::QueryServer<CommSpeechObjects::CommSpeechOutputMessage,CommBasicObjects::CommPropertySet> &s, CHS::QueryId i)
	    : msg(m), query_server(&s), id(i) {}

	    CommSpeechObjects::CommSpeechOutputMessage msg;
	    CHS::QueryServer<CommSpeechObjects::CommSpeechOutputMessage,CommBasicObjects::CommPropertySet> *query_server;
	    CHS::QueryId id;
	  };

	CHS::SmartMutex _queue_mutex;
	CHS::SmartSemaphore _queue_sem;
	std::list<QueueEntry> _queue;

};

#endif
