//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CompHandler.hh"
#include "gen/SmartJoystickNavigation.hh"

#include <iostream>

// include communication objects
#include <CommBasicObjects/commJoystick.hh>

#include <CommBasicObjects/commNavigationVelocity.hh>

void CompHandler::onStartup()
{
	std::cout
			<< "startup - put your startupCode in CompHandler::onStartup()!!!\n";

	CHS::StatusCode status;

	// connect to all services
	std::cout << "connecting to: " << COMP->ini.joystick_client.serverName
			<< "; " << COMP->ini.joystick_client.serviceName << std::endl;
	status = COMP->joystick_client->connect(
			COMP->ini.joystick_client.serverName,
			COMP->ini.joystick_client.serviceName);
	while (status != CHS::SMART_OK)
	{
		usleep(500000);
		status = COMP->joystick_client->connect(
				COMP->ini.joystick_client.serverName,
				COMP->ini.joystick_client.serviceName);
	}
	std::cout << "connected.\n";

	COMP->joystick_client->subscribe();
	std::cout << "connecting to: " << COMP->ini.navigation_client.serverName
			<< "; " << COMP->ini.navigation_client.serviceName << std::endl;
	status = COMP->navigation_client->connect(
			COMP->ini.navigation_client.serverName,
			COMP->ini.navigation_client.serviceName);
	while (status != CHS::SMART_OK)
	{
		usleep(500000);
		status = COMP->navigation_client->connect(
				COMP->ini.navigation_client.serverName,
				COMP->ini.navigation_client.serviceName);
	}
	std::cout << "connected.\n";

	// run all tasks
	COMP->joystickNavigationThread.open();

}
