//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

// --------------------------------------------------------------------------
//
//  Copyright (C) 2003 Boris Kluge
//
//        schlegel@hs-ulm.de
//
//        Prof. Dr. Christian Schlegel
//        University of Applied Sciences
//        Prittwitzstr. 10
//        D-89075 Ulm
//        Germany
//
//  This file is part of the "SmartSoft Basic Communication Classes".
//  It provides basic standardized data types for communication between
//  different components in the mobile robotics context. These classes
//  are designed to be used in conjunction with the SmartSoft Communication
//  Library.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
//  (partly based on work by Christian Schlegel and Pablo d'Angelo)
//
// --------------------------------------------------------------------------

#include "commBasePosition.hh"



using namespace CommBasicObjects;

void CommBasePosition::get(CORBA::Any &a) const
{
	a <<= idl_CommBasePosition;
}

void CommBasePosition::set(const CORBA::Any &a)
{
	CommBasicObjectsIDL::CommBasePosition *tmp_cmd;
	if (a >>= tmp_cmd)
	{
		idl_CommBasePosition = *tmp_cmd;
	}
}







CommBasePosition::CommBasePosition()
{
  idl_CommBasePosition.x = 0;
  idl_CommBasePosition.y = 0;
  idl_CommBasePosition.z = 0;
  idl_CommBasePosition.a_base = 0;
  idl_CommBasePosition.a_steer = 0;
  idl_CommBasePosition.a_turret = 0;

  idl_CommBasePosition.m.length(3*3); // since it is now a corba sequence!

  for(unsigned int i=0; i<3; ++i)
  for(unsigned int j=0; j<3; ++j)
  {
    idl_CommBasePosition.m[i*3+j] = (i==j)?1:0;
  }
  idl_CommBasePosition.cov_invalid = 0;
  idl_CommBasePosition.update_count = 0;
}

CommBasePosition::~CommBasePosition()
{
}



void CommBasePosition::print(std::ostream &os) const
{
  // FIXME: check this
  os << "CommBasePosition(p=(x=" << idl_CommBasePosition.x << ",y=" << idl_CommBasePosition.y << ",z=" << idl_CommBasePosition.z
     << ",base_alpha=" << idl_CommBasePosition.a_base << ",steer_alpha=" << idl_CommBasePosition.a_steer << ",turret_alpha=" << idl_CommBasePosition.a_turret << "),"
     << "m=((" << idl_CommBasePosition.m[0] << "," << idl_CommBasePosition.m[1] << "," << idl_CommBasePosition.m[2] << "),"
     <<    "(" << idl_CommBasePosition.m[3] << "," << idl_CommBasePosition.m[4] << "," << idl_CommBasePosition.m[5] << "),"
     <<    "(" << idl_CommBasePosition.m[6] << "," << idl_CommBasePosition.m[7] << "," << idl_CommBasePosition.m[8] << ")),"
     << "idl_CommBasePosition.cov_invalid= "<< idl_CommBasePosition.cov_invalid << "," << "upd_cnt=" << idl_CommBasePosition.update_count << ")";
}

void CommBasePosition::save_xml(std::ostream &os, const std::string &indent) const
{
  os << indent << "<base_position>" << std::endl;
  os << indent << "  <x>" << idl_CommBasePosition.x << "</x>" << std::endl;
  os << indent << "  <y>" << idl_CommBasePosition.y << "</y>" << std::endl;
  os << indent << "  <z>" << idl_CommBasePosition.z << "</z>" << std::endl;
  os << indent << "  <alpha_base>" << idl_CommBasePosition.a_base << "</alpha_base>" << std::endl;
  os << indent << "  <alpha_steer>" << idl_CommBasePosition.a_steer << "</alpha_steer>" << std::endl;
  os << indent << "  <alpha_turret>" << idl_CommBasePosition.a_turret << "</alpha_turret>" << std::endl;
  os << indent << "  <cov_invalid>" << idl_CommBasePosition.cov_invalid << "</cov_invalid>" << std::endl;
  os << indent << "  <update_count>" << idl_CommBasePosition.update_count << "</update_count>" << std::endl;
  for(unsigned int i=0; i<9; ++i)
  {
    // FIXME: check this
    os << indent << "  <cov i=\"" << i%3 << "\" j=\"" << i/3 << "\">" << idl_CommBasePosition.m[i] << "</cov>" << std::endl;
  }
  os << indent << "</base_position>" << std::endl;
}

void CommBasePosition::load_xml(std::istream &is)
{
  static const Smart::KnuthMorrisPratt kmp_begin("<base_position>");
  static const Smart::KnuthMorrisPratt kmp_x("<x>");
  static const Smart::KnuthMorrisPratt kmp_y("<y>");
  static const Smart::KnuthMorrisPratt kmp_z("<z>");
  static const Smart::KnuthMorrisPratt kmp_alpha_base("<alpha_base>");
  static const Smart::KnuthMorrisPratt kmp_alpha_steer("<alpha_steer>");
  static const Smart::KnuthMorrisPratt kmp_alpha_turret("<alpha_turret>");
  static const Smart::KnuthMorrisPratt kmp_cov_invalid("<cov_invalid>");
  static const Smart::KnuthMorrisPratt kmp_update_count("<update_count>");
  static const Smart::KnuthMorrisPratt kmp_cov("\">");
  static const Smart::KnuthMorrisPratt kmp_end("</base_position>");

  kmp_begin.search(is);
  kmp_x.search(is);
  is >> idl_CommBasePosition.x;
  kmp_y.search(is);
  is >> idl_CommBasePosition.y;
  kmp_z.search(is);
  is >> idl_CommBasePosition.z;
  kmp_alpha_base.search(is);
  is >> idl_CommBasePosition.a_base;
  kmp_alpha_steer.search(is);
  is >> idl_CommBasePosition.a_steer;
  kmp_alpha_turret.search(is);
  is >> idl_CommBasePosition.a_turret;
  kmp_cov_invalid.search(is);
  is >> idl_CommBasePosition.cov_invalid;
  kmp_update_count.search(is);
  is >> idl_CommBasePosition.update_count;
  for(unsigned int i=0; i<9; ++i)
  {
    kmp_cov.search(is);
    is >> idl_CommBasePosition.m[i];
  }
  kmp_end.search(is);
}


