//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.2
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _GOALEVENTHANDLER_HH
#define _GOALEVENTHANDLER_HH

#include "smartSoft.hh"

// include communication objects
#include <CommBasicObjects/commDevicePoseState.hh>

#include <CommPTUObjects/commPTUGoalEventParameter.hh>

#include <CommPTUObjects/commPTUGoalEventResult.hh>

#include <CommPTUObjects/commPTUMoveRequest.hh>

#include <CommPTUObjects/commPTUMoveResponse.hh>

#include <CommPTUObjects/commPTUParameter.hh>

#include "gen/GoalEventHandlerCore.hh"

class GoalEventHandler: public GoalEventHandlerCore
{
	void handleEvent(const CHS::EventId id,
			const CommPTUObjects::CommPTUGoalEventResult &r) throw();
};

#endif
