//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.6.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the workflow to re-generate this file, please
// delete it before running the workflow.
//--------------------------------------------------------------------------

#ifndef _NAVIGATIONVELOCITYSENDSERVERHANDLER_HH
#define _NAVIGATIONVELOCITYSENDSERVERHANDLER_HH

#include "smartSoft.hh"

#include "gen/NavigationVelocitySendServerHandlerCore.hh"

class NavigationVelocitySendServerHandler: public NavigationVelocitySendServerHandlerCore
{
	void handleSend(const CommBasicObjects::CommNavigationVelocity &r) throw();
};

#endif
