//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.6.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the workflow to re-generate this file, please
// delete it before running the workflow.
//------------------------------------------------------------------------
//
//  Copyright (C) 2010 Manuel Wopfner
//
//        wopfner@hs-ulm.de
//
//        Christian Schlegel (schlegel@hs-ulm.de)
//        University of Applied Sciences
//        Prittwitzstr. 10
//        89075 Ulm (Germany)
//
//  This file is part of the "CommManipulatorObjects".
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//--------------------------------------------------------------------------

#ifndef _COMM_COMMMANIPULATOREVENTPARAMETER_HH
#define _COMM_COMMMANIPULATOREVENTPARAMETER_HH

#include <string>

// include header-files of includes communication objects
#include <CommManipulatorObjects/gen/enumManipulatorEvent.hh>

// include client-side file generated by IDL compiler
#include "CommManipulatorObjects/gen/smartCommManipulatorEventParameterC.hh"

namespace CommManipulatorObjects {

class CommManipulatorEventParameter {
protected:
	CommManipulatorObjectsIDL::CommManipulatorEventParameter idl_CommManipulatorEventParameter;

public:
	CommManipulatorEventParameter() {
	}

	CommManipulatorEventParameter(const CommManipulatorObjectsIDL::CommManipulatorEventParameter &obj) :
		idl_CommManipulatorEventParameter(obj) {
	}

	virtual ~CommManipulatorEventParameter() {
	}

	void get(CORBA::Any &a) const;
	void set(const CORBA::Any &a);

	inline const CommManipulatorObjectsIDL::CommManipulatorEventParameter &get() const {
		return idl_CommManipulatorEventParameter;
	}

	inline void set(const CommManipulatorObjectsIDL::CommManipulatorEventParameter &obj) {
		idl_CommManipulatorEventParameter = obj;
	}

	static inline std::string identifier(void) {
		return "CommManipulatorObjects::CommManipulatorEventParameter";
	}

	//
	// user interfaces

	/**
	 * Set the event in which the user expects the component to be.
	 */
	inline void set_event(CommManipulatorObjects::ManipulatorEvent event) {
		idl_CommManipulatorEventParameter.event = event.get_value_idl();
	}

	/**
	 * Get the event in which the user expects the component to be.
	 */
	inline CommManipulatorObjects::ManipulatorEvent get_event() const {
		return (CommManipulatorObjects::ManipulatorEvent) idl_CommManipulatorEventParameter.event;
	}

};

}
#endif
