//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.6.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//------------------------------------------------------------------------
//
//  Copyright (C) 2010 Manuel Wopfner
//
//        wopfner@hs-ulm.de
//
//        Christian Schlegel (schlegel@hs-ulm.de)
//        University of Applied Sciences
//        Prittwitzstr. 10
//        89075 Ulm (Germany)
//
//  This file is part of the "SmartKatana component".
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//--------------------------------------------------------------------------

#include "CompHandler.hh"
#include "gen/SmartKatanaServer.hh"

#include <iostream>

// include communication objects
#include <CommVisionObjects/comm3dPointCloud.hh>
#include <CommManipulatorObjects/commManipulatorEventParameter.hh>
#include <CommManipulatorObjects/commManipulatorEventResult.hh>
#include <CommManipulatorObjects/manipulatorEventState.hh>
#include <CommManipulatorObjects/commManipulatorId.hh>
#include <CommManipulatorObjects/commManipulatorParameter.hh>
#include <CommManipulatorObjects/commManipulatorRequestScan3d.hh>
#include <CommManipulatorObjects/commManipulatorTrajectory.hh>
#include <CommManipulatorObjects/commMobileManipulatorState.hh>

#include "Katana.hh"

void CompHandler::onStartup() {
	std::cout << "Component is starting ...\n";

	////////////////////////////
	// Startup Code for Katana
	////////////////////////////

	KATANA->init();

	//////////////////////
	// Other startup code
	//////////////////////

	CHS::StatusCode status;

	// connect to all services

	// connect to baseServer if it is activated in the ini file
	if (COMP->ini.base.on_base) {
		std::cout << "connecting to: " << COMP->ini.basePushTimedClient.serverName << "; "
				<< COMP->ini.basePushTimedClient.serviceName << std::endl;
		status = COMP->basePushTimedClient->connect(COMP->ini.basePushTimedClient.serverName,
				COMP->ini.basePushTimedClient.serviceName);
		while (status != CHS::SMART_OK) {
			usleep(500000);
			status = COMP->basePushTimedClient->connect(COMP->ini.basePushTimedClient.serverName,
					COMP->ini.basePushTimedClient.serviceName);
		}
		std::cout << "connected.\n";

		COMP->basePushTimedClient->subscribe(COMP->ini.basePushTimedClient.interval);
	}

	// connect to laserServer if it is activated in the ini file
	if (COMP->ini.laser.laser_is_mounted) {
		std::cout << "connecting to: " << COMP->ini.laserQueryClient.serverName << "; "
				<< COMP->ini.laserQueryClient.serviceName << std::endl;
		status = COMP->laserQueryClient->connect(COMP->ini.laserQueryClient.serverName,
				COMP->ini.laserQueryClient.serviceName);
		while (status != CHS::SMART_OK) {
			usleep(500000);
			status = COMP->laserQueryClient->connect(COMP->ini.laserQueryClient.serverName,
					COMP->ini.laserQueryClient.serviceName);
		}
		std::cout << "connected.\n";
	}

	// activate state server
	if (COMP->stateServer->activate() != CHS::SMART_OK)
		std::cerr << "ERROR: activate state" << std::endl;

	std::cout << "Component started ...\n";
}
