//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.6.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _SCAN3DHANDLER_HH
#define _SCAN3DHANDLER_HH

#include "smartSoft.hh"

// include communication objects
#include <CommVisionObjects/comm3dPointCloud.hh>
#include <CommManipulatorObjects/commManipulatorEventParameter.hh>
#include <CommManipulatorObjects/commManipulatorEventResult.hh>
#include <CommManipulatorObjects/manipulatorEventState.hh>
#include <CommManipulatorObjects/commManipulatorId.hh>
#include <CommManipulatorObjects/commManipulatorParameter.hh>
#include <CommManipulatorObjects/commManipulatorRequestScan3d.hh>
#include <CommManipulatorObjects/commManipulatorTrajectory.hh>
#include <CommManipulatorObjects/commMobileManipulatorState.hh>
#include "gen/Scan3dHandlerCore.hh"

class Scan3dHandler: public Scan3dHandlerCore
{
	void handleQuery(CHS::QueryServer<CommManipulatorObjects::CommManipulatorId,
			CommVisionObjects::Comm3dPointCloud> & server, const CHS::QueryId id,
			const CommManipulatorObjects::CommManipulatorId & request) throw();
};

#endif
