//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.6.0
// The SmartSoft Toolchain has been developed by:
//  
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
// 
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#ifndef _SCANEVENTTESTHANDLER_HH
#define _SCANEVENTTESTHANDLER_HH

#include "smartSoft.hh"

// include communication objects
#include "externalCommObjectHeaders.hh"
#include <comm3dPointCloud.hh>
#include <commManipulatorEventParameter.hh>
#include <commManipulatorEventResult.hh>
#include <commManipulatorId.hh>
#include <commManipulatorParameter.hh>
#include <commManipulatorRequestScan3d.hh>
#include <commManipulatorTrajectory.hh>
#include <commMobileManipulatorState.hh>
#include <manipulatorEventState.hh>
#include <scanEventState.hh>

#include "gen/ScanEventTestHandlerCore.hh"

class ScanEventTestHandler: public ScanEventTestHandlerCore
{
	bool testEvent(Smart::CommVoid &p, Smart::CommManipulatorId &r,
			const Smart::ScanEventState &s) throw();
};

#endif
