#!/bin/sh
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain Version 0.10.4
# The SmartSoft Toolchain has been developed by:
#  
# ZAFH Servicerobotic Ulm
# Christian Schlegel (schlegel@hs-ulm.de)
# University of Applied Sciences
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# smart-robotics.sourceforge.net
# 
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------

	    
#######
## case
case "$1" in
	    
	    
#########################################################################################
## start
start)
    	
### protected region for startup code			
# PROTECTED REGION ID(CustomUserStartupCode) ENABLED START
# put your custom startup code here
# PROTECTED REGION END    	
	    
## start naming service
if [ `ps -Al | grep -c Naming_Service` -eq 1 ]
then 
	echo "shuttting down CORBA Naming Service ..."
	killall Naming_Service
	echo "starting CORBA Naming Service ..."
	$TAO_ROOT/orbsvcs/Naming_Service/Naming_Service -m 0 -ORBEndpoint iiop://localhost:12345 &
	echo "CORBA Naming Service is running!"
else 
	echo "starting CORBA Naming Service ..."
	$TAO_ROOT/orbsvcs/Naming_Service/Naming_Service -m 0 -ORBEndpoint iiop://localhost:12345 &
	echo "CORBA Naming Service is running!"
fi




## start components
echo "starting components..."
xterm -e $SMART_ROOT/bin/smartCdlServer -filename=SmartCdlServer.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartJoystickNavigation -filename=SmartJoystickNavigation.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartJoystickServer -filename=SmartJoystickServer.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartMapperGridMap -filename=SmartMapperGridMap.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartPlannerBreadthFirstSearch -filename=SmartPlannerBreadthFirstSearch.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartROSBaseGateway -filename=SmartROSBaseGateway.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartROSLaserGateway -filename=SmartROSLaserGateway.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartRobotConsole -filename=SmartRobotConsole.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &
xterm -e $SMART_ROOT/bin/smartVisualization -filename=SmartVisualization.ini -ORBInitRef NameService=corbaloc:iiop:localhost:12345/NameService &

;; ## start
		
		
#########################################################################################
## stop
stop)

echo "kill all components..."
killall smartCdlServer
killall smartJoystickNavigation
killall smartJoystickServer
killall smartMapperGridMap
killall smartPlannerBreadthFirstSearch
killall smartROSBaseGateway
killall smartROSLaserGateway
killall smartRobotConsole
killall smartVisualization
## TODO: ssh <username>@<target> 'killall xxx'

if [ `ps -Al | grep -c Naming_Service` -eq 1 ]
then 
  echo "shuttting down CORBA Naming Service ..."
  killall Naming_Service
  echo "CORBA Naming Service is down!"
else 
  echo "CORBA Naming Service is not running!"
fi




### protected region for shutdown code			
# PROTECTED REGION ID(CustomUserShutdownCode) ENABLED START
# put your custom shutdown code here		
# PROTECTED REGION END    
;; ## stop
		
		
		
#########################################################################################
## default
*)
echo "Usage: $0 {start|stop}"
exit 1
;; ## default

esac

