//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.10.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

// --------------------------------------------------------------------------
//
//  Copyright (C) 2011 Manuel Wopfner
//
//        schlegel@hs-ulm.de
//
//        ZAFH Servicerobotik Ulm
//        University of Applied Sciences
//        Prittwitzstr. 10
//        D-89075 Ulm
//        Germany
//
//  This file is part of the "SmartSoft Communication Classes".
//  It provides basic standardized data types for communication between
//  different components in the mobile robotics context. These classes
//  are designed to be used in conjunction with the SmartSoft Communication
//  Library.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --------------------------------------------------------------------------

#include "BaseTask.hh"
#include "gen/SmartVisualization.hh"

#include "CommBasicObjects/commBaseState.hh"

#include <iostream>

BaseTask::BaseTask() :
	base(0) {
}

void BaseTask::init() {
	base = new BaseVisualization(COMP->getWindow3d(), "Base");
}

int BaseTask::svc() {
	std::cout << "connecting to: " << COMP->ini.baseClient.serverName << "; " << COMP->ini.baseClient.serviceName << std::endl;
	CHS::StatusCode status = COMP->baseClient->connect(COMP->ini.baseClient.serverName, COMP->ini.baseClient.serviceName);
	while (status != CHS::SMART_OK) {
		usleep(500000);
		status = COMP->baseClient->connect(COMP->ini.baseClient.serverName, COMP->ini.baseClient.serviceName);
	}
	std::cout << COMP->ini.baseClient.serverName << "; " << COMP->ini.baseClient.serviceName << " connected.\n";
	COMP->baseClient->subscribe(COMP->ini.baseClient.interval);

	if (base != 0) {
		while (1) {
			CommBasicObjects::CommBaseState baseState;
			CHS::StatusCode status = COMP->baseClient->getUpdateWait(baseState);
			if (status == CHS::SMART_OK) {
				base->displayBase(baseState);
			} else {
				base->clear();
			}
		}
		delete base;
	} else {
		std::cerr << "No base visualization available\n";
	}
	return 0;
}
