//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain Version 0.8.0
// The SmartSoft Toolchain has been developed by:
//
// ZAFH Servicerobotic Ulm
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// smart-robotics.sourceforge.net
//
// This file is generated once. Modify this file to your needs.
// If you want the toolchain to re-generate this file, please
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CompHandler.hh"
#include "gen/SmartLaserBaseEmpty.hh"

#include <iostream>

// include communication objects
#include "CommBasicObjects/commMobileLaserScan.hh"
#include "CommBasicObjects/commNavigationVelocity.hh"

void CompHandler::onStartup()
{
	std::cout
			<< "startup - put your startupCode in CompHandler::onStartup()!!!\n";

	CHS::StatusCode status;

	// connect to all services
	std::cout << "connecting to: " << COMP->ini.navVelSendClient.serverName
			<< "; " << COMP->ini.navVelSendClient.serviceName << std::endl;
	status = COMP->navVelSendClient->connect(
			COMP->ini.navVelSendClient.serverName,
			COMP->ini.navVelSendClient.serviceName);
	while (status != CHS::SMART_OK)
	{
		usleep(500000);
		status = COMP->navVelSendClient->connect(
				COMP->ini.navVelSendClient.serverName,
				COMP->ini.navVelSendClient.serviceName);
	}
	std::cout << "connected.\n";

	std::cout << "connecting to: " << COMP->ini.laserClient.serverName << "; "
			<< COMP->ini.laserClient.serviceName << std::endl;
	status = COMP->laserClient->connect(COMP->ini.laserClient.serverName,
			COMP->ini.laserClient.serviceName);
	while (status != CHS::SMART_OK)
	{
		usleep(500000);
		status = COMP->laserClient->connect(COMP->ini.laserClient.serverName,
				COMP->ini.laserClient.serviceName);
	}
	std::cout << "connected.\n";

	COMP->laserClient->subscribe();

	// start tasks
	/////////////////////////////////////////////////////////////////
	// AUTMSLAB ACHTUNG! Hier darf nur ein Task starten!
	// Je Übung einen eigenen Task nutzen!
	COMP->robotTask.open();
	// COMP->robotTask2.open();
	// COMP->robotTask3.open();
	// COMP->robotTask4.open();
	/////////////////////////////////////////////////////////////////

}
